"""followers

Revision ID: 35526529b148
Revises: 60fc60c9dd23
Create Date: 2020-05-13 11:55:32.899290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35526529b148'
down_revision = '60fc60c9dd23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
